- name: Create Docker network
  docker_network:
    name: my_app_network
    driver: bridge
    state: present

- name: Launch database container
  docker_container:
    name: my_database
    image: postgres:latest
    env:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    networks:
      - name: my_app_network
    state: started
